### ISSUE TITLE
ver que aporta y añadir si es necesario a la pagina SSG google analytics...

### ISSUE THREAD

**Issue by runtimevic** [runtimevic/OOP-IEC61131-3--Curso-Youtube#2]
Hola,
se podria añadir a la pagina SSG google analytics...

**Comment by montselec** [comment]
Hola Victor buscare informacion al respecto y lo veo  un saludo

**Comment by runtimevic** [comment]
Hola, he añadido correctamente google analytics, 
Asi se puede mejorar la documentación gracias a las estadisticas recibidas...
https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
